# Generated by Django 5.2.4 on 2025-09-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_follow'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follow',
            name='profiles_fo_followe_d25a34_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='profiles_fo_followi_73c5f7_idx',
        ),
    ]
