# Generated by Django 5.2.4 on 2025-09-02 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_thread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationstate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_updated_c8bdde_idx',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='chat_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConversationState',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_b',
        ),
    ]
