# Generated by Django 5.2.4 on 2025-08-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylizedimage',
            name='original_image',
            field=models.ImageField(upload_to='inputs/'),
        ),
        migrations.AlterField(
            model_name='stylizedimage',
            name='styled_image',
            field=models.ImageField(upload_to='outputs/'),
        ),
    ]
