# Generated by Django 5.2.4 on 2025-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0002_alter_stylizedimage_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylizedimage',
            name='original_image',
            field=models.ImageField(upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='stylizedimage',
            name='styled_image',
            field=models.ImageField(upload_to='output/'),
        ),
    ]
