# Generated by Django 5.2.4 on 2025-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0003_alter_stylizedimage_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylizedimage',
            name='original_image',
            field=models.ImageField(max_length=255, upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='stylizedimage',
            name='styled_image',
            field=models.ImageField(max_length=255, upload_to='output/'),
        ),
    ]
